language: ruby
rvm: 
- 2.3.3
before_install:
 - rvm @global do gem uninstall bundler -v 1.14.4 -x
 - rvm @global do gem install bundler -v 1.13.7 -x
 - bundle --version
script:
  - bundle exec rake db:reset
  - bundle exec rake spec
  - bundle exec rake spinach
cache: bundler
services:
  - postgresql
addons:
  postgresql: '9.4'
notificatations:
  slack: 
    rooms:
      - togodeliveryapp:9NMcWbSV1NpZZ6TOre3KLVuL#general
